 services:
  
  extract:
    build: 
      context: ./Extract
      dockerfile: ./.dockerfile
    image: extract:latest

  transform:
    build: 
      context: ./Transform
      dockerfile: ./.dockerfile
    image: transform:latest
